### ISSUE TITLE
Getting crash when 'Keep schedule' is enabled but the stop doesn't exist anymore.

### ISSUE THREAD

**Issue by Be-Cool-Man** [S3bulon/railway-motor-car#1]
The mod Railway Motor Car (0.3.5) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event railway-motor-car::railway-motor-car-key (ID 211)
Given entity doesn't exist anymore.
stack traceback:
	[C]: in function '__newindex'
	__railway-motor-car__/scripts/use_equipment.lua:86: in function 'mount'
	__railway-motor-car__/scripts/use_equipment.lua:115: in function <__railway-motor-car__/scripts/use_equipment.lua:105>

**Comment by S3bulon** [comment]
Thanks for the Report.
This was tricky, because it only occurred for temporary stops if the rail below the stop was removed.
Regular stations are fine, because they are stored by their name.

Fixed with 0.3.6
