### ISSUE TITLE
Unrecoverable when in Remote View

### ISSUE THREAD

**Issue by Androviks** [S3bulon/railway-motor-car#3]
When near a rail line (or waterway, if you're using Cargoships) in remote view, accidentally or intentionally pressing the bound key for equipping the RMC causes an unrecoverable crash as it attempts to mount the player to the rail line remotely.

The mod Railway Motor Car (0.5.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event railway-motor-car: railway-motor-car-key (ID 254)
The mod Railway Motor Car (0.5.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event railway-motor-car:on_player_driving_changed_state (ID 29)

__railway-motor-car__/scripts/use_equipment.lua:237: attempt to index field 'vehicle' (a nil value)
stack traceback
__railway-motor-car__/scripts/use_equipment.lua:237: in function <__railway-motor-car__/scripts/use_equipment.lua:210>
stack traceback
[C]: in function 'set_driver'
__railway-motor-car__/scripts/use_equipment.lua:145: in function 'mount'
__railway-motor-car__/scripts/use_equipment.lua:203: in function <__railway-motor-car__/scripts/use_equipment.lua:193>

**Comment by S3bulon** [comment]
Thanks for the report, fixed with 0.5.1
